/*
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lance.namespace.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.lance.namespace.model.DeleteTableVersionsEntry;
import org.lance.namespace.model.Identity;
import org.lance.namespace.model.VersionRange;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Request to delete table version records. Supports deleting ranges of versions for efficient bulk cleanup. This request supports two modes: - Single-table (legacy): Use &#x60;id&#x60; + &#x60;ranges&#x60; to delete versions from one table. - Multi-table (transactional): Use &#x60;entries&#x60; to atomically delete versions   across multiple tables in a single operation. When &#x60;entries&#x60; is provided, &#x60;id&#x60; and &#x60;ranges&#x60; are ignored. 
 */
@JsonPropertyOrder({
  BatchDeleteTableVersionsRequest.JSON_PROPERTY_IDENTITY,
  BatchDeleteTableVersionsRequest.JSON_PROPERTY_CONTEXT,
  BatchDeleteTableVersionsRequest.JSON_PROPERTY_ID,
  BatchDeleteTableVersionsRequest.JSON_PROPERTY_RANGES,
  BatchDeleteTableVersionsRequest.JSON_PROPERTY_ENTRIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class BatchDeleteTableVersionsRequest {
  public static final String JSON_PROPERTY_IDENTITY = "identity";
  @javax.annotation.Nullable
  private Identity identity;

  public static final String JSON_PROPERTY_CONTEXT = "context";
  @javax.annotation.Nullable
  private Map<String, String> context = new HashMap<>();

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private List<String> id = new ArrayList<>();

  public static final String JSON_PROPERTY_RANGES = "ranges";
  @javax.annotation.Nullable
  private List<VersionRange> ranges = new ArrayList<>();

  public static final String JSON_PROPERTY_ENTRIES = "entries";
  @javax.annotation.Nullable
  private List<DeleteTableVersionsEntry> entries = new ArrayList<>();

  public BatchDeleteTableVersionsRequest() {
  }

  public BatchDeleteTableVersionsRequest identity(@javax.annotation.Nullable Identity identity) {
    
    this.identity = identity;
    return this;
  }

  /**
   * Get identity
   * @return identity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Identity getIdentity() {
    return identity;
  }


  @JsonProperty(JSON_PROPERTY_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentity(@javax.annotation.Nullable Identity identity) {
    this.identity = identity;
  }

  public BatchDeleteTableVersionsRequest context(@javax.annotation.Nullable Map<String, String> context) {
    
    this.context = context;
    return this;
  }

  public BatchDeleteTableVersionsRequest putContextItem(String key, String contextItem) {
    if (this.context == null) {
      this.context = new HashMap<>();
    }
    this.context.put(key, contextItem);
    return this;
  }

  /**
   * Arbitrary context for a request as key-value pairs. How to use the context is custom to the specific implementation.  REST NAMESPACE ONLY Context entries are passed via HTTP headers using the naming convention &#x60;x-lance-ctx-&lt;key&gt;: &lt;value&gt;&#x60;. For example, a context entry &#x60;{\&quot;trace_id\&quot;: \&quot;abc123\&quot;}&#x60; would be sent as the header &#x60;x-lance-ctx-trace_id: abc123&#x60;. 
   * @return context
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getContext() {
    return context;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContext(@javax.annotation.Nullable Map<String, String> context) {
    this.context = context;
  }

  public BatchDeleteTableVersionsRequest id(@javax.annotation.Nullable List<String> id) {
    
    this.id = id;
    return this;
  }

  public BatchDeleteTableVersionsRequest addIdItem(String idItem) {
    if (this.id == null) {
      this.id = new ArrayList<>();
    }
    this.id.add(idItem);
    return this;
  }

  /**
   * The table identifier (single-table mode, legacy). Ignored when &#x60;entries&#x60; is provided. 
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable List<String> id) {
    this.id = id;
  }

  public BatchDeleteTableVersionsRequest ranges(@javax.annotation.Nullable List<VersionRange> ranges) {
    
    this.ranges = ranges;
    return this;
  }

  public BatchDeleteTableVersionsRequest addRangesItem(VersionRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

  /**
   * List of version ranges to delete (single-table mode, legacy). Ignored when &#x60;entries&#x60; is provided. Each range specifies start (inclusive) and end (exclusive) versions. 
   * @return ranges
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VersionRange> getRanges() {
    return ranges;
  }


  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRanges(@javax.annotation.Nullable List<VersionRange> ranges) {
    this.ranges = ranges;
  }

  public BatchDeleteTableVersionsRequest entries(@javax.annotation.Nullable List<DeleteTableVersionsEntry> entries) {
    
    this.entries = entries;
    return this;
  }

  public BatchDeleteTableVersionsRequest addEntriesItem(DeleteTableVersionsEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<>();
    }
    this.entries.add(entriesItem);
    return this;
  }

  /**
   * List of per-table delete entries for multi-table transactional deletion. When provided, the operation atomically deletes versions across all specified tables. 
   * @return entries
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DeleteTableVersionsEntry> getEntries() {
    return entries;
  }


  @JsonProperty(JSON_PROPERTY_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntries(@javax.annotation.Nullable List<DeleteTableVersionsEntry> entries) {
    this.entries = entries;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BatchDeleteTableVersionsRequest batchDeleteTableVersionsRequest = (BatchDeleteTableVersionsRequest) o;
    return Objects.equals(this.identity, batchDeleteTableVersionsRequest.identity) &&
        Objects.equals(this.context, batchDeleteTableVersionsRequest.context) &&
        Objects.equals(this.id, batchDeleteTableVersionsRequest.id) &&
        Objects.equals(this.ranges, batchDeleteTableVersionsRequest.ranges) &&
        Objects.equals(this.entries, batchDeleteTableVersionsRequest.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identity, context, id, ranges, entries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BatchDeleteTableVersionsRequest {\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `identity` to the URL query string
    if (getIdentity() != null) {
      joiner.add(getIdentity().toUrlQueryString(prefix + "identity" + suffix));
    }

    // add `context` to the URL query string
    if (getContext() != null) {
      for (String _key : getContext().keySet()) {
        try {
          joiner.add(String.format("%scontext%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
              getContext().get(_key), URLEncoder.encode(String.valueOf(getContext().get(_key)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `id` to the URL query string
    if (getId() != null) {
      for (int i = 0; i < getId().size(); i++) {
        try {
          joiner.add(String.format("%sid%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getId().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `ranges` to the URL query string
    if (getRanges() != null) {
      for (int i = 0; i < getRanges().size(); i++) {
        if (getRanges().get(i) != null) {
          joiner.add(getRanges().get(i).toUrlQueryString(String.format("%sranges%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `entries` to the URL query string
    if (getEntries() != null) {
      for (int i = 0; i < getEntries().size(); i++) {
        if (getEntries().get(i) != null) {
          joiner.add(getEntries().get(i).toUrlQueryString(String.format("%sentries%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

