/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lance.namespace.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Result of a single operation within a batch commit. Each result corresponds to one operation in
 * the request, in the same order.
 */
@JsonPropertyOrder({
  CommitTableResult.JSON_PROPERTY_TYPE,
  CommitTableResult.JSON_PROPERTY_ID,
  CommitTableResult.JSON_PROPERTY_LOCATION,
  CommitTableResult.JSON_PROPERTY_VERSION,
  CommitTableResult.JSON_PROPERTY_DELETED_COUNT
})
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.12.0")
@JsonIgnoreProperties(
    value =
        "type", // ignore manually set type, it will be automatically generated by Jackson during
    // serialization
    allowSetters = true // allows the type to be set during deserialization
    )
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(
      value = CommitTableResultCreateTableVersion.class,
      name = "create_table_version"),
  @JsonSubTypes.Type(value = CommitTableResultDeclareTable.class, name = "declare_table"),
  @JsonSubTypes.Type(
      value = CommitTableResultDeleteTableVersions.class,
      name = "delete_table_versions"),
  @JsonSubTypes.Type(value = CommitTableResultDeregisterTable.class, name = "deregister_table"),
  @JsonSubTypes.Type(
      value = CommitTableResultCreateTableVersion.class,
      name = "CommitTableResultCreateTableVersion"),
  @JsonSubTypes.Type(
      value = CommitTableResultDeclareTable.class,
      name = "CommitTableResultDeclareTable"),
  @JsonSubTypes.Type(
      value = CommitTableResultDeleteTableVersions.class,
      name = "CommitTableResultDeleteTableVersions"),
  @JsonSubTypes.Type(
      value = CommitTableResultDeregisterTable.class,
      name = "CommitTableResultDeregisterTable"),
})
public class CommitTableResult {
  /** Gets or Sets type */
  public enum TypeEnum {
    DECLARE_TABLE(String.valueOf("declare_table")),

    CREATE_TABLE_VERSION(String.valueOf("create_table_version")),

    DELETE_TABLE_VERSIONS(String.valueOf("delete_table_versions")),

    DEREGISTER_TABLE(String.valueOf("deregister_table"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull private TypeEnum type;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull private List<String> id = new ArrayList<>();

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nullable private String location;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull private TableVersion version;

  public static final String JSON_PROPERTY_DELETED_COUNT = "deleted_count";
  @javax.annotation.Nonnull private Long deletedCount;

  public CommitTableResult() {}

  public CommitTableResult type(@javax.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public CommitTableResult id(@javax.annotation.Nonnull List<String> id) {

    this.id = id;
    return this;
  }

  public CommitTableResult addIdItem(String idItem) {
    if (this.id == null) {
      this.id = new ArrayList<>();
    }
    this.id.add(idItem);
    return this;
  }

  /**
   * The table identifier
   *
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull List<String> id) {
    this.id = id;
  }

  public CommitTableResult location(@javax.annotation.Nullable String location) {

    this.location = location;
    return this;
  }

  /**
   * The storage location of the deregistered table
   *
   * @return location
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLocation() {
    return location;
  }

  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@javax.annotation.Nullable String location) {
    this.location = location;
  }

  public CommitTableResult version(@javax.annotation.Nonnull TableVersion version) {

    this.version = version;
    return this;
  }

  /**
   * The created table version details
   *
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TableVersion getVersion() {
    return version;
  }

  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull TableVersion version) {
    this.version = version;
  }

  public CommitTableResult deletedCount(@javax.annotation.Nonnull Long deletedCount) {

    this.deletedCount = deletedCount;
    return this;
  }

  /**
   * Number of version records deleted minimum: 0
   *
   * @return deletedCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DELETED_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getDeletedCount() {
    return deletedCount;
  }

  @JsonProperty(JSON_PROPERTY_DELETED_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeletedCount(@javax.annotation.Nonnull Long deletedCount) {
    this.deletedCount = deletedCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitTableResult commitTableResult = (CommitTableResult) o;
    return Objects.equals(this.type, commitTableResult.type)
        && Objects.equals(this.id, commitTableResult.id)
        && Objects.equals(this.location, commitTableResult.location)
        && Objects.equals(this.version, commitTableResult.version)
        && Objects.equals(this.deletedCount, commitTableResult.deletedCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, location, version, deletedCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitTableResult {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    deletedCount: ").append(toIndentedString(deletedCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(
            String.format(
                "%stype%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `id` to the URL query string
    if (getId() != null) {
      for (int i = 0; i < getId().size(); i++) {
        try {
          joiner.add(
              String.format(
                  "%sid%s%s=%s",
                  prefix,
                  suffix,
                  "".equals(suffix)
                      ? ""
                      : String.format("%s%d%s", containerPrefix, i, containerSuffix),
                  URLEncoder.encode(String.valueOf(getId().get(i)), "UTF-8")
                      .replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `location` to the URL query string
    if (getLocation() != null) {
      try {
        joiner.add(
            String.format(
                "%slocation%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getLocation()), "UTF-8")
                    .replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(getVersion().toUrlQueryString(prefix + "version" + suffix));
    }

    // add `deleted_count` to the URL query string
    if (getDeletedCount() != null) {
      try {
        joiner.add(
            String.format(
                "%sdeleted_count%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getDeletedCount()), "UTF-8")
                    .replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }
}
