/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.lance.namespace.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * A single operation within a batch commit. Uses a discriminator on the &#x60;type&#x60; field to
 * determine the operation kind.
 */
@JsonPropertyOrder({
  CommitTableOperation.JSON_PROPERTY_TYPE,
  CommitTableOperation.JSON_PROPERTY_ID,
  CommitTableOperation.JSON_PROPERTY_LOCATION,
  CommitTableOperation.JSON_PROPERTY_PROPERTIES,
  CommitTableOperation.JSON_PROPERTY_VERSION,
  CommitTableOperation.JSON_PROPERTY_MANIFEST_PATH,
  CommitTableOperation.JSON_PROPERTY_MANIFEST_SIZE,
  CommitTableOperation.JSON_PROPERTY_E_TAG,
  CommitTableOperation.JSON_PROPERTY_METADATA,
  CommitTableOperation.JSON_PROPERTY_NAMING_SCHEME,
  CommitTableOperation.JSON_PROPERTY_RANGES
})
@javax.annotation.Generated(
    value = "org.openapitools.codegen.languages.JavaClientCodegen",
    comments = "Generator version: 7.12.0")
@JsonIgnoreProperties(
    value =
        "type", // ignore manually set type, it will be automatically generated by Jackson during
    // serialization
    allowSetters = true // allows the type to be set during deserialization
    )
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
    visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(
      value = CommitTableOperationCreateTableVersion.class,
      name = "create_table_version"),
  @JsonSubTypes.Type(value = CommitTableOperationDeclareTable.class, name = "declare_table"),
  @JsonSubTypes.Type(
      value = CommitTableOperationDeleteTableVersions.class,
      name = "delete_table_versions"),
  @JsonSubTypes.Type(value = CommitTableOperationDeregisterTable.class, name = "deregister_table"),
  @JsonSubTypes.Type(
      value = CommitTableOperationCreateTableVersion.class,
      name = "CommitTableOperationCreateTableVersion"),
  @JsonSubTypes.Type(
      value = CommitTableOperationDeclareTable.class,
      name = "CommitTableOperationDeclareTable"),
  @JsonSubTypes.Type(
      value = CommitTableOperationDeleteTableVersions.class,
      name = "CommitTableOperationDeleteTableVersions"),
  @JsonSubTypes.Type(
      value = CommitTableOperationDeregisterTable.class,
      name = "CommitTableOperationDeregisterTable"),
})
public class CommitTableOperation {
  /** Gets or Sets type */
  public enum TypeEnum {
    DECLARE_TABLE(String.valueOf("declare_table")),

    CREATE_TABLE_VERSION(String.valueOf("create_table_version")),

    DELETE_TABLE_VERSIONS(String.valueOf("delete_table_versions")),

    DEREGISTER_TABLE(String.valueOf("deregister_table"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull private TypeEnum type;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull private List<String> id = new ArrayList<>();

  public static final String JSON_PROPERTY_LOCATION = "location";
  @javax.annotation.Nullable private String location;

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @javax.annotation.Nullable private Map<String, String> properties = new HashMap<>();

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull private Long version;

  public static final String JSON_PROPERTY_MANIFEST_PATH = "manifest_path";
  @javax.annotation.Nonnull private String manifestPath;

  public static final String JSON_PROPERTY_MANIFEST_SIZE = "manifest_size";
  @javax.annotation.Nullable private Long manifestSize;

  public static final String JSON_PROPERTY_E_TAG = "e_tag";
  @javax.annotation.Nullable private String eTag;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable private Map<String, String> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_NAMING_SCHEME = "naming_scheme";
  @javax.annotation.Nullable private String namingScheme;

  public static final String JSON_PROPERTY_RANGES = "ranges";
  @javax.annotation.Nonnull private List<VersionRange> ranges = new ArrayList<>();

  public CommitTableOperation() {}

  public CommitTableOperation type(@javax.annotation.Nonnull TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }

  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public CommitTableOperation id(@javax.annotation.Nonnull List<String> id) {

    this.id = id;
    return this;
  }

  public CommitTableOperation addIdItem(String idItem) {
    if (this.id == null) {
      this.id = new ArrayList<>();
    }
    this.id.add(idItem);
    return this;
  }

  /**
   * The table identifier
   *
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getId() {
    return id;
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull List<String> id) {
    this.id = id;
  }

  public CommitTableOperation location(@javax.annotation.Nullable String location) {

    this.location = location;
    return this;
  }

  /**
   * Optional storage location for the table
   *
   * @return location
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLocation() {
    return location;
  }

  @JsonProperty(JSON_PROPERTY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocation(@javax.annotation.Nullable String location) {
    this.location = location;
  }

  public CommitTableOperation properties(
      @javax.annotation.Nullable Map<String, String> properties) {

    this.properties = properties;
    return this;
  }

  public CommitTableOperation putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * Optional table properties
   *
   * @return properties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getProperties() {
    return properties;
  }

  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@javax.annotation.Nullable Map<String, String> properties) {
    this.properties = properties;
  }

  public CommitTableOperation version(@javax.annotation.Nonnull Long version) {

    this.version = version;
    return this;
  }

  /**
   * Version number to create minimum: 0
   *
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Long getVersion() {
    return version;
  }

  @JsonProperty(JSON_PROPERTY_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull Long version) {
    this.version = version;
  }

  public CommitTableOperation manifestPath(@javax.annotation.Nonnull String manifestPath) {

    this.manifestPath = manifestPath;
    return this;
  }

  /**
   * Path to the manifest file for this version
   *
   * @return manifestPath
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MANIFEST_PATH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getManifestPath() {
    return manifestPath;
  }

  @JsonProperty(JSON_PROPERTY_MANIFEST_PATH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setManifestPath(@javax.annotation.Nonnull String manifestPath) {
    this.manifestPath = manifestPath;
  }

  public CommitTableOperation manifestSize(@javax.annotation.Nullable Long manifestSize) {

    this.manifestSize = manifestSize;
    return this;
  }

  /**
   * Size of the manifest file in bytes minimum: 0
   *
   * @return manifestSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANIFEST_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getManifestSize() {
    return manifestSize;
  }

  @JsonProperty(JSON_PROPERTY_MANIFEST_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManifestSize(@javax.annotation.Nullable Long manifestSize) {
    this.manifestSize = manifestSize;
  }

  public CommitTableOperation eTag(@javax.annotation.Nullable String eTag) {

    this.eTag = eTag;
    return this;
  }

  /**
   * Optional ETag for the manifest file
   *
   * @return eTag
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_E_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String geteTag() {
    return eTag;
  }

  @JsonProperty(JSON_PROPERTY_E_TAG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void seteTag(@javax.annotation.Nullable String eTag) {
    this.eTag = eTag;
  }

  public CommitTableOperation metadata(@javax.annotation.Nullable Map<String, String> metadata) {

    this.metadata = metadata;
    return this;
  }

  public CommitTableOperation putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Optional metadata for the version
   *
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getMetadata() {
    return metadata;
  }

  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public CommitTableOperation namingScheme(@javax.annotation.Nullable String namingScheme) {

    this.namingScheme = namingScheme;
    return this;
  }

  /**
   * The naming scheme used for manifest files in the &#x60;_versions/&#x60; directory. Known
   * values: - &#x60;V1&#x60;: &#x60;_versions/{version}.manifest&#x60; - Simple version-based
   * naming - &#x60;V2&#x60;: &#x60;_versions/{inverted_version}.manifest&#x60; - Zero-padded,
   * reversed version number (uses &#x60;u64::MAX - version&#x60;) for O(1) lookup of latest version
   * on object stores V2 is preferred for new tables as it enables efficient latest-version
   * discovery without needing to list all versions.
   *
   * @return namingScheme
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAMING_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNamingScheme() {
    return namingScheme;
  }

  @JsonProperty(JSON_PROPERTY_NAMING_SCHEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamingScheme(@javax.annotation.Nullable String namingScheme) {
    this.namingScheme = namingScheme;
  }

  public CommitTableOperation ranges(@javax.annotation.Nonnull List<VersionRange> ranges) {

    this.ranges = ranges;
    return this;
  }

  public CommitTableOperation addRangesItem(VersionRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

  /**
   * List of version ranges to delete
   *
   * @return ranges
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<VersionRange> getRanges() {
    return ranges;
  }

  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRanges(@javax.annotation.Nonnull List<VersionRange> ranges) {
    this.ranges = ranges;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitTableOperation commitTableOperation = (CommitTableOperation) o;
    return Objects.equals(this.type, commitTableOperation.type)
        && Objects.equals(this.id, commitTableOperation.id)
        && Objects.equals(this.location, commitTableOperation.location)
        && Objects.equals(this.properties, commitTableOperation.properties)
        && Objects.equals(this.version, commitTableOperation.version)
        && Objects.equals(this.manifestPath, commitTableOperation.manifestPath)
        && Objects.equals(this.manifestSize, commitTableOperation.manifestSize)
        && Objects.equals(this.eTag, commitTableOperation.eTag)
        && Objects.equals(this.metadata, commitTableOperation.metadata)
        && Objects.equals(this.namingScheme, commitTableOperation.namingScheme)
        && Objects.equals(this.ranges, commitTableOperation.ranges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        type,
        id,
        location,
        properties,
        version,
        manifestPath,
        manifestSize,
        eTag,
        metadata,
        namingScheme,
        ranges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitTableOperation {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    manifestPath: ").append(toIndentedString(manifestPath)).append("\n");
    sb.append("    manifestSize: ").append(toIndentedString(manifestSize)).append("\n");
    sb.append("    eTag: ").append(toIndentedString(eTag)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    namingScheme: ").append(toIndentedString(namingScheme)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(
            String.format(
                "%stype%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `id` to the URL query string
    if (getId() != null) {
      for (int i = 0; i < getId().size(); i++) {
        try {
          joiner.add(
              String.format(
                  "%sid%s%s=%s",
                  prefix,
                  suffix,
                  "".equals(suffix)
                      ? ""
                      : String.format("%s%d%s", containerPrefix, i, containerSuffix),
                  URLEncoder.encode(String.valueOf(getId().get(i)), "UTF-8")
                      .replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `location` to the URL query string
    if (getLocation() != null) {
      try {
        joiner.add(
            String.format(
                "%slocation%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getLocation()), "UTF-8")
                    .replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `properties` to the URL query string
    if (getProperties() != null) {
      for (String _key : getProperties().keySet()) {
        try {
          joiner.add(
              String.format(
                  "%sproperties%s%s=%s",
                  prefix,
                  suffix,
                  "".equals(suffix)
                      ? ""
                      : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
                  getProperties().get(_key),
                  URLEncoder.encode(String.valueOf(getProperties().get(_key)), "UTF-8")
                      .replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `version` to the URL query string
    if (getVersion() != null) {
      try {
        joiner.add(
            String.format(
                "%sversion%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getVersion()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `manifest_path` to the URL query string
    if (getManifestPath() != null) {
      try {
        joiner.add(
            String.format(
                "%smanifest_path%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getManifestPath()), "UTF-8")
                    .replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `manifest_size` to the URL query string
    if (getManifestSize() != null) {
      try {
        joiner.add(
            String.format(
                "%smanifest_size%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getManifestSize()), "UTF-8")
                    .replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `e_tag` to the URL query string
    if (geteTag() != null) {
      try {
        joiner.add(
            String.format(
                "%se_tag%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(geteTag()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      for (String _key : getMetadata().keySet()) {
        try {
          joiner.add(
              String.format(
                  "%smetadata%s%s=%s",
                  prefix,
                  suffix,
                  "".equals(suffix)
                      ? ""
                      : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
                  getMetadata().get(_key),
                  URLEncoder.encode(String.valueOf(getMetadata().get(_key)), "UTF-8")
                      .replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `naming_scheme` to the URL query string
    if (getNamingScheme() != null) {
      try {
        joiner.add(
            String.format(
                "%snaming_scheme%s=%s",
                prefix,
                suffix,
                URLEncoder.encode(String.valueOf(getNamingScheme()), "UTF-8")
                    .replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `ranges` to the URL query string
    if (getRanges() != null) {
      for (int i = 0; i < getRanges().size(); i++) {
        if (getRanges().get(i) != null) {
          joiner.add(
              getRanges()
                  .get(i)
                  .toUrlQueryString(
                      String.format(
                          "%sranges%s%s",
                          prefix,
                          suffix,
                          "".equals(suffix)
                              ? ""
                              : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}
