/*
 * Lance Namespace Specification
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.lance.namespace.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.lance.namespace.model.VersionRange;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * An entry for deleting table versions in a batch operation. Each entry specifies a table and the version ranges to delete. 
 */
@JsonPropertyOrder({
  DeleteTableVersionsEntry.JSON_PROPERTY_ID,
  DeleteTableVersionsEntry.JSON_PROPERTY_RANGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class DeleteTableVersionsEntry {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private List<String> id = new ArrayList<>();

  public static final String JSON_PROPERTY_RANGES = "ranges";
  @javax.annotation.Nonnull
  private List<VersionRange> ranges = new ArrayList<>();

  public DeleteTableVersionsEntry() {
  }

  public DeleteTableVersionsEntry id(@javax.annotation.Nonnull List<String> id) {
    
    this.id = id;
    return this;
  }

  public DeleteTableVersionsEntry addIdItem(String idItem) {
    if (this.id == null) {
      this.id = new ArrayList<>();
    }
    this.id.add(idItem);
    return this;
  }

  /**
   * The table identifier
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull List<String> id) {
    this.id = id;
  }

  public DeleteTableVersionsEntry ranges(@javax.annotation.Nonnull List<VersionRange> ranges) {
    
    this.ranges = ranges;
    return this;
  }

  public DeleteTableVersionsEntry addRangesItem(VersionRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

  /**
   * List of version ranges to delete. Each range specifies start (inclusive) and end (exclusive) versions. 
   * @return ranges
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<VersionRange> getRanges() {
    return ranges;
  }


  @JsonProperty(JSON_PROPERTY_RANGES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRanges(@javax.annotation.Nonnull List<VersionRange> ranges) {
    this.ranges = ranges;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteTableVersionsEntry deleteTableVersionsEntry = (DeleteTableVersionsEntry) o;
    return Objects.equals(this.id, deleteTableVersionsEntry.id) &&
        Objects.equals(this.ranges, deleteTableVersionsEntry.ranges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ranges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteTableVersionsEntry {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      for (int i = 0; i < getId().size(); i++) {
        try {
          joiner.add(String.format("%sid%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getId().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `ranges` to the URL query string
    if (getRanges() != null) {
      for (int i = 0; i < getRanges().size(); i++) {
        if (getRanges().get(i) != null) {
          joiner.add(getRanges().get(i).toUrlQueryString(String.format("%sranges%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

