/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlterVirtualColumnEntry {
    /// List of input column names for the virtual column (optional)
    #[serde(rename = "input_columns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub input_columns: Option<Option<Vec<String>>>,
    /// Docker image to use for the UDF (optional)
    #[serde(rename = "image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image: Option<Option<String>>,
    /// Base64 encoded pickled UDF (optional)
    #[serde(rename = "udf", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub udf: Option<Option<String>>,
    /// Name of the UDF (optional)
    #[serde(rename = "udf_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub udf_name: Option<Option<String>>,
    /// Version of the UDF (optional)
    #[serde(rename = "udf_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub udf_version: Option<Option<String>>,
}

impl AlterVirtualColumnEntry {
    pub fn new() -> AlterVirtualColumnEntry {
        AlterVirtualColumnEntry {
            input_columns: None,
            image: None,
            udf: None,
            udf_name: None,
            udf_version: None,
        }
    }
}

