/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchCreateTableVersionsResponse : Response for batch creating table versions. Contains the created versions for each table in the same order as the request. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchCreateTableVersionsResponse {
    /// Optional transaction identifier
    #[serde(rename = "transaction_id", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    /// List of created table versions in the same order as the request entries
    #[serde(rename = "versions")]
    pub versions: Vec<models::TableVersion>,
}

impl BatchCreateTableVersionsResponse {
    /// Response for batch creating table versions. Contains the created versions for each table in the same order as the request. 
    pub fn new(versions: Vec<models::TableVersion>) -> BatchCreateTableVersionsResponse {
        BatchCreateTableVersionsResponse {
            transaction_id: None,
            versions,
        }
    }
}

