/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitTableOperation : A single operation within a batch commit. Uses a discriminator on the `type` field to determine the operation kind. 
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum CommitTableOperation {
    #[serde(rename="declare_table")]
    DeclareTable(Box<models::CommitTableOperationDeclareTable>),
    #[serde(rename="create_table_version")]
    CreateTableVersion(Box<models::CommitTableOperationCreateTableVersion>),
    #[serde(rename="delete_table_versions")]
    DeleteTableVersions(Box<models::CommitTableOperationDeleteTableVersions>),
    #[serde(rename="deregister_table")]
    DeregisterTable(Box<models::CommitTableOperationDeregisterTable>),
}

impl Default for CommitTableOperation {
    fn default() -> Self {
        Self::DeclareTable(Default::default())
    }
}


