/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitTableOperationDeleteTableVersions : Delete version ranges from a table.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitTableOperationDeleteTableVersions {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The table identifier
    #[serde(rename = "id")]
    pub id: Vec<String>,
    /// List of version ranges to delete
    #[serde(rename = "ranges")]
    pub ranges: Vec<models::VersionRange>,
}

impl CommitTableOperationDeleteTableVersions {
    /// Delete version ranges from a table.
    pub fn new(r#type: Type, id: Vec<String>, ranges: Vec<models::VersionRange>) -> CommitTableOperationDeleteTableVersions {
        CommitTableOperationDeleteTableVersions {
            r#type,
            id,
            ranges,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "delete_table_versions")]
    DeleteTableVersions,
}

impl Default for Type {
    fn default() -> Type {
        Self::DeleteTableVersions
    }
}

