/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitTableOperationDeregisterTable : Deregister (soft-delete) a table. The table's physical data remains intact.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitTableOperationDeregisterTable {
    #[serde(rename = "type")]
    pub r#type: Type,
    /// The table identifier
    #[serde(rename = "id")]
    pub id: Vec<String>,
}

impl CommitTableOperationDeregisterTable {
    /// Deregister (soft-delete) a table. The table's physical data remains intact.
    pub fn new(r#type: Type, id: Vec<String>) -> CommitTableOperationDeregisterTable {
        CommitTableOperationDeregisterTable {
            r#type,
            id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "deregister_table")]
    DeregisterTable,
}

impl Default for Type {
    fn default() -> Type {
        Self::DeregisterTable
    }
}

