/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CommitTableOperation : A single operation within a batch commit. Provide exactly one of the operation fields to specify the operation kind. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommitTableOperation {
    /// Declare (reserve) a new table in the namespace
    #[serde(rename = "declare_table", skip_serializing_if = "Option::is_none")]
    pub declare_table: Option<Box<models::DeclareTableRequest>>,
    /// Create a new version entry for a table
    #[serde(rename = "create_table_version", skip_serializing_if = "Option::is_none")]
    pub create_table_version: Option<Box<models::CreateTableVersionRequest>>,
    /// Delete version ranges from a table
    #[serde(rename = "delete_table_versions", skip_serializing_if = "Option::is_none")]
    pub delete_table_versions: Option<Box<models::BatchDeleteTableVersionsRequest>>,
    /// Deregister (soft-delete) a table
    #[serde(rename = "deregister_table", skip_serializing_if = "Option::is_none")]
    pub deregister_table: Option<Box<models::DeregisterTableRequest>>,
}

impl CommitTableOperation {
    /// A single operation within a batch commit. Provide exactly one of the operation fields to specify the operation kind. 
    pub fn new() -> CommitTableOperation {
        CommitTableOperation {
            declare_table: None,
            create_table_version: None,
            delete_table_versions: None,
            deregister_table: None,
        }
    }
}

