/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeclareTableResponse : Response for declaring a table. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeclareTableResponse {
    /// Optional transaction identifier
    #[serde(rename = "transaction_id", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    /// Configuration options to be used to access storage. The available options depend on the type of storage in use. These will be passed directly to Lance to initialize storage access. 
    #[serde(rename = "storage_options", skip_serializing_if = "Option::is_none")]
    pub storage_options: Option<std::collections::HashMap<String, String>>,
    /// If the implementation does not support table properties, it should return null for this field. Otherwise it should return the properties. 
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
    /// When true, the caller should use namespace table version operations (CreateTableVersion, DescribeTableVersion, ListTableVersions, BatchDeleteTableVersions) to manage table versions instead of relying on Lance's native version management. 
    #[serde(rename = "managed_versioning", skip_serializing_if = "Option::is_none")]
    pub managed_versioning: Option<bool>,
}

impl DeclareTableResponse {
    /// Response for declaring a table. 
    pub fn new() -> DeclareTableResponse {
        DeclareTableResponse {
            transaction_id: None,
            location: None,
            storage_options: None,
            properties: None,
            managed_versioning: None,
        }
    }
}

