/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartitionSpec : Partition spec definition
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartitionSpec {
    /// The spec version ID
    #[serde(rename = "id")]
    pub id: i32,
    /// Array of partition field definitions
    #[serde(rename = "fields")]
    pub fields: Vec<models::PartitionField>,
}

impl PartitionSpec {
    /// Partition spec definition
    pub fn new(id: i32, fields: Vec<models::PartitionField>) -> PartitionSpec {
        PartitionSpec {
            id,
            fields,
        }
    }
}

