/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartitionTransform : Well-known partition transform
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartitionTransform {
    /// Transform type (identity, year, month, day, hour, bucket, multi_bucket, truncate)
    #[serde(rename = "type")]
    pub r#type: String,
    /// Number of buckets for bucket transforms
    #[serde(rename = "num_buckets", skip_serializing_if = "Option::is_none")]
    pub num_buckets: Option<i32>,
    /// Truncation width for truncate transforms
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
}

impl PartitionTransform {
    /// Well-known partition transform
    pub fn new(r#type: String) -> PartitionTransform {
        PartitionTransform {
            r#type,
            num_buckets: None,
            width: None,
        }
    }
}
