/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryTableOrderBy : Ordering of a source field, matching Lance Scanner ColumnOrdering. Multiple entries are evaluated in list order. Strings use UTF-8 binary lexicographic order and floating-point values use IEEE 754 total order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryTableOrderBy {
    /// Source Lance field path to sort by, independent of output aliases. Nested fields use dot-separated segments; use backtick-quoted segments for literal dots and double backticks inside quoted segments.
    #[serde(rename = "column_name")]
    pub column_name: String,
    /// Whether to sort in ascending order.
    #[serde(rename = "ascending", skip_serializing_if = "Option::is_none")]
    pub ascending: Option<bool>,
    /// Whether null values precede non-null values, independent of direction.
    #[serde(rename = "nulls_first", skip_serializing_if = "Option::is_none")]
    pub nulls_first: Option<bool>,
}

impl QueryTableOrderBy {
    /// Ordering of a source field, matching Lance Scanner ColumnOrdering. Multiple entries are evaluated in list order. Strings use UTF-8 binary lexicographic order and floating-point values use IEEE 754 total order.
    pub fn new(column_name: String) -> QueryTableOrderBy {
        QueryTableOrderBy {
            column_name,
            ascending: None,
            nulls_first: None,
        }
    }
}

