/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefreshMaterializedViewRequest {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<models::Identity>>,
    /// Table identifier path (namespace + table name)
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<Vec<String>>,
    /// Optional source version to refresh from
    #[serde(rename = "src_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub src_version: Option<Option<i32>>,
    /// Optional maximum rows per fragment
    #[serde(rename = "max_rows_per_fragment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_rows_per_fragment: Option<Option<i32>>,
    /// Optional concurrency override
    #[serde(rename = "concurrency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub concurrency: Option<Option<i32>>,
    /// Optional intra-applier concurrency override
    #[serde(rename = "intra_applier_concurrency", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub intra_applier_concurrency: Option<Option<i32>>,
    /// Optional cluster name
    #[serde(rename = "cluster", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cluster: Option<Option<String>>,
    /// Optional manifest name
    #[serde(rename = "manifest", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub manifest: Option<Option<String>>,
}

impl RefreshMaterializedViewRequest {
    pub fn new() -> RefreshMaterializedViewRequest {
        RefreshMaterializedViewRequest {
            identity: None,
            id: None,
            src_version: None,
            max_rows_per_fragment: None,
            concurrency: None,
            intra_applier_concurrency: None,
            cluster: None,
            manifest: None,
        }
    }
}

