/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableVersion {
    /// Version number
    #[serde(rename = "version")]
    pub version: i64,
    /// Path to the manifest file for this version. When not provided, the client should resolve the manifest path based on the Lance table format's manifest naming scheme and the manifest naming scheme the table is currently using.
    #[serde(rename = "manifest_path", skip_serializing_if = "Option::is_none")]
    pub manifest_path: Option<String>,
    /// Size of the manifest file in bytes
    #[serde(rename = "manifest_size", skip_serializing_if = "Option::is_none")]
    pub manifest_size: Option<i64>,
    /// Optional ETag for optimistic concurrency control. Useful for S3 and similar object stores.
    #[serde(rename = "e_tag", skip_serializing_if = "Option::is_none")]
    pub e_tag: Option<String>,
    /// Timestamp when the version was created
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    /// Optional key-value pairs of metadata
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

impl TableVersion {
    pub fn new(version: i64) -> TableVersion {
        TableVersion {
            version,
            manifest_path: None,
            manifest_size: None,
            e_tag: None,
            timestamp: None,
            metadata: None,
        }
    }
}
