/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTableResponse {
    /// Optional transaction identifier
    #[serde(rename = "transaction_id", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    /// Number of rows updated
    #[serde(rename = "updated_rows")]
    pub updated_rows: i64,
    /// The commit version associated with the operation
    #[serde(rename = "version")]
    pub version: i64,
    /// If the implementation does not support table properties, it should return null for this field. Otherwise, it should return the properties. 
    #[serde(rename = "properties", skip_serializing_if = "Option::is_none")]
    pub properties: Option<std::collections::HashMap<String, String>>,
}

impl UpdateTableResponse {
    pub fn new(updated_rows: i64, version: i64) -> UpdateTableResponse {
        UpdateTableResponse {
            transaction_id: None,
            updated_rows,
            version,
            properties: None,
        }
    }
}

