/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionRange : A range of versions to delete (start inclusive, end exclusive). Special values: - `start_version: 0` with `end_version: -1` means ALL versions 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionRange {
    /// Start version of the range (inclusive). Use 0 to start from the first version. 
    #[serde(rename = "start_version")]
    pub start_version: i64,
    /// End version of the range (exclusive). Use -1 to indicate all versions up to and including the latest. 
    #[serde(rename = "end_version")]
    pub end_version: i64,
}

impl VersionRange {
    /// A range of versions to delete (start inclusive, end exclusive). Special values: - `start_version: 0` with `end_version: -1` means ALL versions 
    pub fn new(start_version: i64, end_version: i64) -> VersionRange {
        VersionRange {
            start_version,
            end_version,
        }
    }
}

