# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.partition_spec import PartitionSpec

class TestPartitionSpec(unittest.TestCase):
    """PartitionSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartitionSpec:
        """Test PartitionSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PartitionSpec`
        """
        model = PartitionSpec()
        if include_optional:
            return PartitionSpec(
                id = 1,
                fields = [
                    lance_namespace_urllib3_client.models.partition_field.PartitionField(
                        field_id = 'event_year', 
                        source_ids = [1], 
                        transform = lance_namespace_urllib3_client.models.partition_transform.PartitionTransform(
                            type = '', 
                            num_buckets = 56, 
                            width = 56, ), 
                        expression = 'date_part('year', col0)', 
                        result_type = {type=int32}, )
                    ]
            )
        else:
            return PartitionSpec(
                id = 1,
                fields = [
                    lance_namespace_urllib3_client.models.partition_field.PartitionField(
                        field_id = 'event_year', 
                        source_ids = [1], 
                        transform = lance_namespace_urllib3_client.models.partition_transform.PartitionTransform(
                            type = '', 
                            num_buckets = 56, 
                            width = 56, ), 
                        expression = 'date_part('year', col0)', 
                        result_type = {type=int32}, )
                    ],
        )
        """

    def testPartitionSpec(self):
        """Test PartitionSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
