# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lance_namespace_urllib3_client.models.commit_table_operation import CommitTableOperation

class TestCommitTableOperation(unittest.TestCase):
    """CommitTableOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitTableOperation:
        """Test CommitTableOperation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitTableOperation`
        """
        model = CommitTableOperation()
        if include_optional:
            return CommitTableOperation(
                type = 'declare_table',
                id = [
                    ''
                    ],
                location = '',
                properties = {
                    'key' : ''
                    },
                version = 0,
                manifest_path = '',
                manifest_size = 0,
                e_tag = '',
                metadata = {
                    'key' : ''
                    },
                naming_scheme = 'V2',
                ranges = [
                    lance_namespace_urllib3_client.models.version_range.VersionRange(
                        start_version = 56, 
                        end_version = 56, )
                    ]
            )
        else:
            return CommitTableOperation(
                type = 'declare_table',
                id = [
                    ''
                    ],
                version = 0,
                manifest_path = '',
                ranges = [
                    lance_namespace_urllib3_client.models.version_range.VersionRange(
                        start_version = 56, 
                        end_version = 56, )
                    ],
        )
        """

    def testCommitTableOperation(self):
        """Test CommitTableOperation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
