# coding: utf-8

"""
    Lance Namespace Specification

    This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from lance_namespace_urllib3_client.models.commit_table_operation_create_table_version import CommitTableOperationCreateTableVersion
from lance_namespace_urllib3_client.models.commit_table_operation_declare_table import CommitTableOperationDeclareTable
from lance_namespace_urllib3_client.models.commit_table_operation_delete_table_versions import CommitTableOperationDeleteTableVersions
from lance_namespace_urllib3_client.models.commit_table_operation_deregister_table import CommitTableOperationDeregisterTable
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

COMMITTABLEOPERATION_ONE_OF_SCHEMAS = ["CommitTableOperationCreateTableVersion", "CommitTableOperationDeclareTable", "CommitTableOperationDeleteTableVersions", "CommitTableOperationDeregisterTable"]

class CommitTableOperation(BaseModel):
    """
    A single operation within a batch commit. Uses a discriminator on the `type` field to determine the operation kind. 
    """
    # data type: CommitTableOperationDeclareTable
    oneof_schema_1_validator: Optional[CommitTableOperationDeclareTable] = None
    # data type: CommitTableOperationCreateTableVersion
    oneof_schema_2_validator: Optional[CommitTableOperationCreateTableVersion] = None
    # data type: CommitTableOperationDeleteTableVersions
    oneof_schema_3_validator: Optional[CommitTableOperationDeleteTableVersions] = None
    # data type: CommitTableOperationDeregisterTable
    oneof_schema_4_validator: Optional[CommitTableOperationDeregisterTable] = None
    actual_instance: Optional[Union[CommitTableOperationCreateTableVersion, CommitTableOperationDeclareTable, CommitTableOperationDeleteTableVersions, CommitTableOperationDeregisterTable]] = None
    one_of_schemas: Set[str] = { "CommitTableOperationCreateTableVersion", "CommitTableOperationDeclareTable", "CommitTableOperationDeleteTableVersions", "CommitTableOperationDeregisterTable" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = CommitTableOperation.model_construct()
        error_messages = []
        match = 0
        # validate data type: CommitTableOperationDeclareTable
        if not isinstance(v, CommitTableOperationDeclareTable):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommitTableOperationDeclareTable`")
        else:
            match += 1
        # validate data type: CommitTableOperationCreateTableVersion
        if not isinstance(v, CommitTableOperationCreateTableVersion):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommitTableOperationCreateTableVersion`")
        else:
            match += 1
        # validate data type: CommitTableOperationDeleteTableVersions
        if not isinstance(v, CommitTableOperationDeleteTableVersions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommitTableOperationDeleteTableVersions`")
        else:
            match += 1
        # validate data type: CommitTableOperationDeregisterTable
        if not isinstance(v, CommitTableOperationDeregisterTable):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CommitTableOperationDeregisterTable`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in CommitTableOperation with oneOf schemas: CommitTableOperationCreateTableVersion, CommitTableOperationDeclareTable, CommitTableOperationDeleteTableVersions, CommitTableOperationDeregisterTable. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in CommitTableOperation with oneOf schemas: CommitTableOperationCreateTableVersion, CommitTableOperationDeclareTable, CommitTableOperationDeleteTableVersions, CommitTableOperationDeregisterTable. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into CommitTableOperationDeclareTable
        try:
            instance.actual_instance = CommitTableOperationDeclareTable.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommitTableOperationCreateTableVersion
        try:
            instance.actual_instance = CommitTableOperationCreateTableVersion.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommitTableOperationDeleteTableVersions
        try:
            instance.actual_instance = CommitTableOperationDeleteTableVersions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CommitTableOperationDeregisterTable
        try:
            instance.actual_instance = CommitTableOperationDeregisterTable.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into CommitTableOperation with oneOf schemas: CommitTableOperationCreateTableVersion, CommitTableOperationDeclareTable, CommitTableOperationDeleteTableVersions, CommitTableOperationDeregisterTable. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into CommitTableOperation with oneOf schemas: CommitTableOperationCreateTableVersion, CommitTableOperationDeclareTable, CommitTableOperationDeleteTableVersions, CommitTableOperationDeregisterTable. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], CommitTableOperationCreateTableVersion, CommitTableOperationDeclareTable, CommitTableOperationDeleteTableVersions, CommitTableOperationDeregisterTable]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


