/*
 * Lance Namespace Specification
 *
 * This OpenAPI specification is a part of the Lance namespace specification. It contains 2 parts:  The `components/schemas`, `components/responses`, `components/examples`, `tags` sections define the request and response shape for each operation in a Lance Namespace across all implementations. See https://lance.org/format/namespace/operations for more details.  The `servers`, `security`, `paths`, `components/parameters` sections are for the  Lance REST Namespace implementation, which defines a complete REST server that can work with Lance datasets. See https://lance.org/format/namespace/rest for more details.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use std::sync::Arc;
use async_trait::async_trait;

/// Middleware for processing requests before they are sent.
///
/// Implementations can modify the request, such as adding headers.
/// This is useful for dynamic authentication tokens that need to be
/// refreshed periodically.
#[async_trait]
pub trait RequestMiddleware: Send + Sync + std::fmt::Debug {
    /// Process a request before it is sent.
    ///
    /// The implementation should return the (possibly modified) request.
    async fn process(&self, request: reqwest::Request) -> reqwest::Request;
}

#[derive(Clone)]
pub struct Configuration {
    pub base_path: String,
    pub user_agent: Option<String>,
    pub client: reqwest::Client,
    pub basic_auth: Option<BasicAuth>,
    pub oauth_access_token: Option<String>,
    pub bearer_access_token: Option<String>,
    pub api_key: Option<ApiKey>,
    /// Optional middleware for processing requests before they are sent.
    pub request_middleware: Option<Arc<dyn RequestMiddleware>>,
}

impl std::fmt::Debug for Configuration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Omit potentially sensitive tokens/keys
        f.debug_struct("Configuration")
            .field("base_path", &self.base_path)
            .field("user_agent", &self.user_agent)
            .field("request_middleware", &self.request_middleware)
            .finish()
    }
}

pub type BasicAuth = (String, Option<String>);

#[derive(Debug, Clone)]
pub struct ApiKey {
    pub prefix: Option<String>,
    pub key: String,
}


impl Configuration {
    pub fn new() -> Configuration {
        Configuration::default()
    }

    /// Execute a request, applying any configured middleware first.
    pub async fn execute(&self, request: reqwest::Request) -> Result<reqwest::Response, reqwest::Error> {
        let request = match &self.request_middleware {
            Some(middleware) => middleware.process(request).await,
            None => request,
        };
        self.client.execute(request).await
    }
}

impl Default for Configuration {
    fn default() -> Self {
        Configuration {
            base_path: "http://localhost:2333".to_owned(),
            user_agent: Some("OpenAPI-Generator/1.0.0/rust".to_owned()),
            client: reqwest::Client::new(),
            basic_auth: None,
            oauth_access_token: None,
            bearer_access_token: None,
            api_key: None,
            request_middleware: None,
        }
    }
}
